missed a couple of ending loop and if statement closes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,8 +23,8 @@ workflows:
           #   - run-check
           context: cimg-publishing
       - check-digests:
-          # requires:
-          #   - push-checks
+          requires:
+            - push-checks
           context: cimg-publishing
 
 
@@ -48,6 +48,7 @@ jobs:
                 echo "Image $i was not built"
                 exit 1
               fi
+            done
   run-check:
     docker:
       - image: cimg/base:2022.06
@@ -65,12 +66,14 @@ jobs:
             for i in $IMAGES; do
               echo "Testing $i"
               VERSION=$(echo $i | cut -d ":" -f 2 | cut -d "-" -f 1)
-              if docker run --platform linux/amd64 -i $i /bin/bash -c 'go version | grep -i $VERSION'; then
-                echo "version check passed"
+              VER_CHECK=$(docker run --platform linux/amd64 -i $i /bin/bash -c 'go version | grep -q -i $VERSION; echo $?)
+              if [ $VER_CHECK -ne 0 ]; then
+                echo "version check passed for $i"
               else
-                echo "version check failed"
+                echo "version check failed for $i"
                 exit 1
               fi
+            done
   push-checks:
     docker:
       - image: cimg/base:2022.06
@@ -98,7 +101,7 @@ jobs:
           paths:
             - digest.txt
       - store_artifacts:
-          path: /tmp/digest
+          path: /tmp/digest.txt
   check-digests:
     docker:
       - image: cimg/base:2022.06
@@ -121,5 +124,6 @@ jobs:
                 else
                   echo "Digest check failed:"
                   exit 1
+                fi
               fi
             done
